[project]
name = "ola"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "kagglehub[pandas-datasets]",
  "pandas",
  "psycopg2-binary",
  "pyarrow",
  "pymongo",
  "python-dotenv",
  "pytest",
  "ruff",
  "sqlalchemy",
  "sqlfluff",
  "great-expectations>=1.23.2",
  "streamlit>=1.64.0",
  "dbt-core>=1.12.5",
  "dbt-postgres>=1.11.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[tool.ruff.lint.per-file-ignores]
"dags/*.py" = ["BLE001", "DTZ001"]
"dashboard/pages/*.py" = ["E402"]
