[project]
name = "ola"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "kagglehub[pandas-datasets]",
  "pandas",
  "psycopg2-binary",
  "pyarrow",
  "pymongo",
  "python-dotenv",
  "pytest",
  "ruff",
  "sqlalchemy",
  "great-expectations>=1.23.2",
]

[tool.pytest.ini_options]
pythonpath = ["."]
